defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - .*
  - Gemfile
  - Gemfile.lock

redcarpet:
  extensions:
    - autolink
    - tables

sass:
  sass_dir: css
  style: nested
  deploy_style: nested
