name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: deploy
        shell: bash
        run: |
          echo "Getting SSH key..."
          curl -fsSo /tmp/ssh-key -H  "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" "${{ vars.SECRET_URL }}"
          chmod 600 /tmp/ssh-key

          echo "Syncing files..."
          rsync -rz --delete -e "${{ vars.RSYNC_CONNECT_PROG }}" ./_site/ "${{ vars.RSYNC_TARGET }}"
